# Generated by Django 3.1.5 on 2021-03-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('js', 'Js')], max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Owner')])),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(through='file_manager.UserFiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
