# Generated by Django 3.1.5 on 2021-03-10 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(related_name='files', through='file_manager.UserFiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='file_manager.file'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
