# Generated by Django 3.1.5 on 2021-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_auto_20210310_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Insert'), (1, 'Delete')])),
                ('position', models.IntegerField()),
                ('text', models.TextField()),
                ('revision', models.IntegerField()),
            ],
        ),
    ]
