# Generated by Django 3.1.5 on 2021-04-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_file_default_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='default_access',
            new_name='link_access',
        ),
    ]
