# Generated by Django 3.1.5 on 2021-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_auto_20210407_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operations',
            name='channel_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operations',
            name='type',
            field=models.IntegerField(choices=[(0, 'Neu'), (1, 'Insert'), (2, 'Delete')]),
        ),
    ]
