# Generated by Django 3.1.5 on 2021-04-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_auto_20210415_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='file_manager.file'),
            preserve_default=False,
        ),
    ]
