# Generated by Django 3.1.5 on 2021-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_operations_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='channel_name',
            field=models.TextField(),
        ),
    ]
